---
# Роль: master_nodes - метаданные

galaxy_info:
  author: DevOps Team
  description: master_nodes role for Slurm HPC cluster
  min_ansible_version: 2.15
  
  platforms:
    - name: Ubuntu
      versions:
        - 24.04

dependencies: []
