# roles/common/defaults/main.yml - Common role configuration variables
---
common_base_packages:
  - build-essential
  - git
  - curl
  - wget
  - vim
  - htop
  - tree
  - rsync
  - python3-dev
  - pkg-config
  - libtool
  - autotools-dev
  - autoconf
  - automake
  - cmake
  - gcc
  - g++
  - make
  - libssl-dev
  - libcurl4-openssl-dev
  - libjson-c-dev
  - libhttp-parser-dev
  - libjwt-dev

timezone: "UTC"

slurm_user: "slurm"
slurm_uid: 59901
slurm_group: "slurm"
slurm_gid: 59901

nfs_export_dirs:
  - /home
  - /sw

nfs_export_options: "rw,sync,no_root_squash"
nfs_mount_options: "defaults"

common_verify_installation: true
common_verify_timeout: 30

# Master node references (used across roles)
master_nodes_host: "{{ groups['master_nodes'][0] }}"
master_nodes_addr: "{{ hostvars[groups['master_nodes'][0]]['ansible_default_ipv4']['address'] | default(groups['master_nodes'][0]) }}"

# NFS paths
nfs_slurm_path: "/sw/slurm-final"
nfs_config_path: "/sw/config"

# Slurm config files to distribute
slurm_config_files:
  - slurm.conf
  - slurmdbd.conf
  - gres.conf