---
- name: Копируем шаблон node-exporter unit
  template:
    src: docker.node-exporter.service.j2
    dest: /etc/systemd/system/docker.node-exporter.service
    mode: '0644'
  notify: Перезапустить node-exporter

- name: Создаем каталог textfile_collector
  file:
    path: /opt/node-exporter/textfile_collector
    state: directory
    mode: '0755'

- name: Включаем и запускаем node-exporter
  systemd:
    name: docker.node-exporter.service
    enabled: true
    state: started
    daemon_reload: true