---
# roles/common/tasks/hosts.yml - Автоматическое формирование /etc/hosts
- name: "Generate /etc/hosts from inventory"
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes
    mode: '0644'
  tags: hosts